apiVersion: v1
kind: Pod
metadata:
  name: jumpod
spec:
  containers:
  - name: shell
    image: centos:7
    command:
      - "bin/bash"
      - "-c"
      - "yum -y install bind-utils && sleep 10000"
